#!/bin/sh -e

cd ..

echo ""
echo ""
echo "################################################################"
echo "#### BUILDING APP"
echo "################################################################"
echo ""
echo ""

go build

echo ""
echo ""
echo "################################################################"
echo "#### UPLOADING TO SERVER"
echo "################################################################"
echo ""
echo ""

rsync -rlpt -vz --progress ./flat-grabber nedgrab:/root/flat-grabber

echo ""
echo ""
echo "################################################################"
echo "#### RESTARTING UNIT"
echo "################################################################"
echo ""
echo ""

ssh -t nedgrab -C "sudo systemctl restart nedgrab;journalctl -n 128 -f -u nedgrab"
